replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/gidraff-cloudkite-58sdk3/fitflow-repo/fitflow-api
  pullPolicy: Always
  tag: "60a3b62ba778fdb1c55a8233957b06b708fcc42f"

service:
  type: ClusterIP
  port: 8081

database:
  name: "fitflow_db"
  secretName: "fitflow-secrets"
  # Replace with: project-id:region:instance-id
  connectionName: "gidraff-cloudkite-58sdk3:us-central1:cordiafit-db"

keycloak:
  # Internal K8s DNS for Keycloak v2
  issuerUrl: "http://keycloak-v2.keycloak.svc.cluster.local/realms/trainer-app"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  name: "fitflow-api-sa"
  # Annotations to add to the service account (useful for Workload Identity)
  annotations: {
    iam.gke.io/gcp-service-account: "fitflow-api-gsa@gidraff-cloudkite-58sdk3.iam.gserviceaccount.com"
  }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template

  # Add this for the deployment.yaml probes/resources
autoscaling:
  enabled: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# These are often used in the ingress.yaml template
ingress:
  enabled: true
  className: "gce" # Use "gce" for Google Cloud Load Balancer or "nginx" if using NGINX controller
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: "fitflow-api-ip" # Name of your reserved GCP Static IP
    networking.gke.io/managed-certificates: "cordiafit-ingress-ip" # If using Google-managed SSL
  hosts:
    - host: api.cordiafit.fit
      paths:
        - path: /
          pathType: Prefix